env:
  - GO111MODULE=on
  - CGO_ENABLED=0

builds:
  - binary: clx.bin
    id: clx
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X "main.version={{ .Tag }} ({{ .ShortCommit }} {{ .Date }})"
    dir: ./

archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE
